### ISSUE TITLE
Hugh security issue

### ISSUE THREAD

**Issue by md2perpe** [FutureGlobeOfficial/SepaSwitch#2]
I sent you the following security issue in a mail to support@futureglobe.de on May 18, but since you seem not to have taken action, I now post it here:

I found that your extension contained the access token. That's a huge security issue.

Actually, I managed to authenticate to the Marketplace using it. I know that it is probably a breach but what I ended up doing was just republishing your extension without the access token inside it.

You should:
- recall the current access token,
- create a new access token,
- not store the new access token inside the extension directory.

**Comment by Futureglobe** [comment]
Hi @md2perpe,

first of all thank you for the hint. There was a problem with our internal versioning tool. The file shouldn't be inside the extension directory. We revoked the access token and created a new one used for publishing.
